# Generated by Django 4.1.5 on 2023-01-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_categoryuser_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='board.PostCategory', to='board.category', verbose_name='Категория'),
        ),
    ]
