# Generated by Django 4.1.5 on 2023-01-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(null=True, through='board.PostCategory', to='board.category', verbose_name='Категория'),
        ),
    ]
